CREATE TABLE notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    title TEXT NOT NULL,
    content TEXT,
    folder_id INTEGER REFERENCES folders(id)
    date_modified timestamp NOT NULL DEFAULT now()
);